
"use client";

import { useAuth } from "@/contexts/AuthContext";
import { SidebarTrigger } from "@/components/ui/sidebar";
import { AceMascot } from "@/components/AceMascot";
import { useEffect, useState } from "react";
import { Flame, Palette } from "lucide-react";
import { db } from "@/lib/firebase";
import { doc, onSnapshot } from "firebase/firestore";
import { timezones } from "@/lib/timezones";
import { DashboardCustomizer } from "@/components/DashboardCustomizer";

const quotes = [
  "Success is the sum of small efforts, repeated day in and day out.",
  "The expert in anything was once a beginner.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
    "Don’t watch the clock; do what it does. Keep going.",
    "Push yourself, because no one else is going to do it for you.",
    "Dream big and dare to fail.",
    "You don’t have to be perfect to be amazing.",
    "Little by little, a little becomes a lot.",
    "Don’t let what you cannot do interfere with what you can do.",
    "Great things never come from comfort zones.",
    "Your only limit is your mind.",
    "Make today so awesome that yesterday gets jealous.",
    "Focus on progress, not perfection.",
    "You are stronger than you think.",
    "The best way to predict the future is to create it.",
    "Discipline is doing what needs to be done, even if you don’t want to do it.",
    "You don’t need motivation every day — you need consistency.",
    "Every accomplishment starts with the decision to try.",
    "Wake up with determination. Go to bed with satisfaction.",
    "The secret to getting ahead is getting started.",
    "It always seems impossible until it’s done.",
    "Small progress is still progress.",
    "Work hard in silence, let success make the noise.",
    "Learning is never done without mistakes.",
    "Study while others are sleeping. Learn while others are partying.",
    "Education is the passport to the future.",
    "Effort is the key to unlock your potential.",
    "You were born to learn, not to give up.",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
    "Be the hardest worker in the room.",
    "What you learn today will shape your tomorrow.",
    "Don't limit your challenges — challenge your limits.",
    "You miss 100% of the shots you don’t take.",
    "It’s not about having time, it’s about making time.",
    "There is no elevator to success — you have to take the stairs.",
    "Study now, shine later.",
    "A little progress each day adds up to big results.",
    "Mistakes are proof you are trying.",
    "Education is the most powerful weapon you can use to change the world.",
    "Nothing will work unless you do.",
    "Champions keep playing until they get it right.",
    "Push past the pressure — it’s how diamonds are made.",
    "Fall seven times, stand up eight.",
    "Success starts with self-discipline.",
    "Don’t count the days — make the days count.",
    "Think like a proton — always positive.",
    "Be proud of how far you've come, and have faith in how far you can go.",
    "Learning never exhausts the mind.",
    "You don't get what you wish for. You get what you work for.",
    "Stay focused and never give up.",
    "Smart work beats hard work when hard work stops working.",
    "Keep your head high and your grades higher.",
    "Doubt kills more dreams than failure ever will.",
    "Be curious. Be committed. Be consistent.",
    "One hour of study now = one hour of freedom later.",
    "You're not behind — you're building.",
    "Procrastination makes easy things hard and hard things harder.",
    "Study like you mean it. The results will show.",
    "Don't be afraid to fail. Be afraid not to try.",
    "Every day is a new chance to grow.",
    "Talent is nothing without dedication.",
    "Your mindset is your superpower.",
    "Success is earned, not given.",
    "You’re allowed to struggle. You’re not allowed to quit.",
    "The struggle you're in today builds the strength you need for tomorrow.",
    "Start where you are. Use what you have. Do what you can.",
    "Set goals. Crush them. Repeat.",
    "Success begins with self-belief.",
    "Keep grinding — your future self is watching.",
    "Dream it. Work for it. Achieve it.",
    "Be patient — good things take time.",
    "Your habits define your outcome.",
    "Stay hungry. Stay humble. Stay focused.",
    "Focus is the key to everything.",
    "A goal without a plan is just a wish.",
    "Motivation gets you started. Habit keeps you going.",
    "Stay consistent. Results take time.",
    "There is no such thing as failure — only feedback.",
    "It’s okay to take breaks — just don’t quit.",
    "Think big, start small, act now.",
    "Turn pressure into power.",
    "You don’t have to be the best — just better than yesterday.",
    "Study because your dreams are worth it.",
    "If you’re tired, learn to rest, not quit.",
    "Effort over excuses.",
    "Keep your eyes on the prize, not the obstacles.",
    "Be stubborn about your goals, but flexible in your methods.",
    "Success isn’t luck — it’s earned.",
    "What seems hard now will one day be your warm-up.",
    "You’re capable of amazing things.",
    "You’ve got this. One step at a time.",
    "Some days you win. Some days you learn.",
    "Winners are just learners who never quit.",
    "If not now, when?",
    "Be the student who refuses to give up.",
    "You don’t grow when you’re comfortable.",
    "Confidence comes from preparation.",
    "Show up. Work hard. Stay kind.",
    "You are not behind. You are exactly where you need to be.",
    "Your future self will thank you for what you do today.",
    // Continued here:
    "Keep pushing forward even when it feels hard.",
    "Every expert was once a beginner who didn’t quit.",
    "Believe in your ability to achieve great things.",
    "A little effort each day leads to big results tomorrow.",
    "Stay focused; distractions are your biggest enemy.",
    "Hard work beats talent when talent doesn’t work hard.",
    "Mistakes mean you’re learning, so keep going.",
    "Consistency is the foundation of success.",
    "Challenges help you grow stronger and smarter.",
    "The journey of a thousand miles begins with one step.",
    "Don’t compare your progress to others, only to yourself.",
    "Your attitude determines your altitude.",
    "Failure is not the opposite of success, it’s part of it.",
    "Success belongs to those who keep trying.",
    "Be brave enough to start, and strong enough to finish.",
    "Keep your goals clear and your mindset positive.",
    "When you feel like quitting, remember why you started.",
    "Education opens doors no one can close.",
    "Every day is a fresh start, make it count.",
    "Push your limits; that’s where growth happens.",
    "Believe in yourself even when no one else does.",
    "Your dreams are worth the effort it takes.",
    "Keep learning, keep growing, keep thriving.",
    "Success is a marathon, not a sprint.",
    "Stay humble, stay hungry, keep improving.",
    "The difference between try and triumph is a little umph.",
    "Your effort today creates your future tomorrow.",
    "The best investment you can make is in yourself.",
    "Don't wait for opportunity. Create it.",
    "The hardest part is showing up — do it anyway.",
    "You control your destiny with every choice you make.",
    "Push beyond your fears and doubts.",
    "A focused mind can move mountains.",
    "Never stop being curious and asking questions.",
    "Keep chasing your dreams no matter what.",
    "Use setbacks as setups for comebacks.",
    "The pain of discipline is less than the pain of regret.",
    "Celebrate small wins along the way.",
    "Learn from yesterday, live for today, hope for tomorrow.",
    "Your potential is endless if you keep trying.",
    "Believe that you can and you’re halfway there.",
    "Success requires sacrifice and dedication.",
    "Your attitude shapes your experience.",
    "The harder you work, the luckier you get.",
    "You are capable of far more than you realize.",
    "Stay patient and trust the process.",
    "Never let fear stop you from reaching your goals.",
    "Work hard silently, let your success be your noise.",
    "Education is the key that unlocks your future.",
    "Persistence beats resistance.",
    "The best way out is always through.",
    "Success is built on daily habits.",
    "Keep your eyes on the prize, not the pain.",
    "Progress is progress, no matter how small.",
    "You are your only limit.",
    "Never underestimate the power of yet.",
    "Stay strong, stay focused, stay motivated.",
    "The best way to learn is to keep trying.",
    "Be the energy you want to attract.",
    "Push yourself, because no one else will do it for you.",
    "The future depends on what you do today.",
    "Don’t quit — great things take time.",
    "Your hard work will pay off, stay consistent.",
    "Dreams don’t work unless you do.",
    "Embrace challenges as opportunities to grow.",
    "Believe in the power of your dreams.",
    "Success is the result of preparation and effort.",
    "Take pride in how far you’ve come.",
    "The journey is as important as the destination.",
    "Stay motivated, even when no one is watching.",
    "Your determination is your greatest asset.",
    "Push through the doubt and the fear.",
    "Small steps every day lead to big changes.",
    "You’ve got the power to change your story.",
    "Stay committed and watch yourself grow.",
    "The only limit is the one you set yourself.",
    "Work hard, dream big, never give up.",
    "Success is earned one step at a time.",
    "Let your passion fuel your progress.",
    "Great things take time and effort.",
    "Keep your focus sharp and your mindset strong.",
    "Every day is an opportunity to improve.",
    "Don’t stop until you’re proud.",
    "You are stronger than any obstacle.",
    "Success is built on resilience and grit.",
    "Stay inspired, stay driven, stay you.",
    "Your future is created by what you do today.",
    "Be the change you want to see in your grades.",
    "Keep working quietly, let your results speak.",
    "The best is yet to come.",
    "You can achieve anything if you put your mind to it.",
    "Hard work today leads to success tomorrow.",
    "Stay disciplined and you will succeed.",
    "Your effort defines your success.",
    "The key to success is consistency.",
    "Learn more, achieve more, be more.",
    "Stay positive, work hard, make it happen.",
    "You are capable of greatness.",
    "Never settle for less than your best.",
    "Believe in the power of perseverance.",
    "Your success story starts with effort.",
    "Every moment is a chance to improve.",
    "Stay focused and make every second count.",
    "Success is a journey, not a destination.",
    "Keep pushing forward with purpose.",
    "The best things in life require hard work.",
    "You hold the pen to your success story.",
    "Keep going, your breakthrough is near.",
    "Believe, work, achieve.",
    "Hard times build strong people.",
    "The difference between who you are and who you want to be is what you do.",
    "Success is no accident.",
    "Make your education your priority.",
    "Your commitment is your power.",
    "Keep your dreams bigger than your fears.",
    "Stay focused and chase your goals.",
    "You’re stronger than you think you are.",
    "Hard work compounds over time.",
    "Stay motivated and the results will follow.",
    "Your passion is your greatest strength.",
    "Success favors the brave.",
    "Keep learning, keep pushing, keep winning.",
    "Never stop believing in yourself.",
    "Take every opportunity to grow.",
    "Your hard work is your best investment.",
    "Stay humble, work hard, be kind.",
    "You control your future with every choice.",
    "Make every day count.",
    "Success starts with self-discipline and focus.",
    "You have the power to make your dreams real.",
    "Keep striving for excellence.",
    "Don’t let fear stop your progress.",
    "Stay dedicated and unstoppable.",
    "Your potential is limitless.",
    "Make progress, not excuses.",
    "Success is built one brick at a time.",
    "Dream big, work hard, stay focused.",
    "Every effort counts toward your success.",
    "Keep your goals in sight and work tirelessly.",
    "Never give up on what matters to you.",
    "The only way to do great work is to start.",
    "Your journey to success begins now.",
    "Focus, work, and never give up.",
    "Success is the result of relentless effort.",
    "Stay determined, stay successful.",
    "Your future is bright if you keep trying.",
    "Every setback is a setup for a comeback.",
    "Success comes to those who never quit.",
    "Keep moving forward no matter what.",
    "Believe in your dreams and pursue them.",
    "Your hard work will create your future.",
    "Make each day a step toward success.",
    "Stay patient and trust your progress.",
    "Keep your mindset positive and strong.",
    "Success is earned with sweat and determination.",
    "Push yourself beyond your limits.",
    "Your dedication will take you far.",
    "Stay focused and achieve your dreams.",
    "Success is built through persistence.",
    "Work hard, stay humble, dream big.",
    "You can do it, one step at a time.",
    "Never stop working for what you want.",
    "Your journey is unique, own it.",
    "Stay confident and keep pushing.",
    "Success is the sum of small efforts.",
    "Keep striving, keep succeeding.",
    "Believe, work, achieve, repeat.",
    "You’re capable of more than you know.",
    "Every day is a chance to be better.",
    "The best way to learn is by doing.",
    "Stay hungry for knowledge.",
    "Work hard now, enjoy later.",
    "Dreams become reality with action.",
    "You’re stronger than any challenge.",
    "Stay positive and keep moving.",
    "Success requires courage and effort.",
    "Be the reason you succeed.",
    "Keep your eyes on the prize.",
    "Stay focused and keep grinding.",
    "Make your success inevitable.",
    "Push through and never quit.",
    "Your effort today shapes tomorrow.",
    "Success is waiting for you.",
    "Work smart and work hard.",
    "Believe in the power of effort.",
    "Your dedication will pay off.",
    "Keep moving forward with purpose.",
    "Never stop learning and growing.",
    "Success comes from persistence.",
    "Stay committed to your goals.",
    "Your journey is just beginning.",
    "Keep fighting for your dreams.",
    "Success is built on determination.",
    "Dream it. Believe it. Achieve it.",
    "Your effort defines your future.",
    "Stay strong and keep going.",
    "Work hard, dream big, succeed.",
    "You have what it takes.",
    "Never give up on yourself.",
    "Success is within your reach.",
    "Keep pushing, keep winning.",
    "Believe in your strength.",
    "Stay focused and be unstoppable.",
    "Make every day your masterpiece.",
    "Your success story is waiting.",
    "Work hard in silence, let success speak.",
    "Keep climbing, keep succeeding.",
    "Dream big and keep working.",
    "Success follows effort.",
    "You are capable of greatness.",
    "Stay determined and achieve.",
    "Work hard, stay focused, win.",
    "Your goals are worth it.",
    "Believe, achieve, succeed.",
    "Keep going, no matter what.",
    "Success is the sum of your actions.",
    "Stay motivated and inspired.",
    "Your future is bright.",
    "Keep striving for the best.",
    "You can do anything.",
    "Never quit on your dreams.",
    "Work hard, stay positive.",
    "Success is yours to claim.",
    "Keep moving, keep winning.",
    "Believe in your journey.",
    "Stay focused and confident.",
    "Make progress every day.",
    "Your effort creates success.",
    "Work smart, work hard.",
    "Dream big, work hard.",
    "Keep pushing, never stop.",
    "Success is earned daily.",
    "You’re stronger than you think.",
    "Stay motivated and driven.",
    "Your dedication pays off.",
    "Keep striving and thriving.",
    "Believe in your power.",
    "Work hard, dream big.",
    "Success is possible for you.",
    "Never stop working.",
    "Stay focused and determined.",
    "Your future is in your hands.",
    "Keep grinding and winning.",
    "Believe, work, succeed.",
    "Success is a journey.",
    "You can achieve greatness.",
    "Stay patient and persistent.",
    "Work hard and believe.",
    "Dream big and act.",
    "Keep pushing forward.",
    "Your success is waiting.",
    "Stay positive and strong.",
    "Work hard and never quit.",
    "Believe in yourself.",
    "Success is earned, not given.",
    "Keep moving forward.",
    "Your efforts will pay off.",
    "Work hard and achieve.",
    "Dream big and focus.",
    "Stay dedicated and strong.",
    "Success is within reach.",
    "Believe and achieve.",
    "Keep going, stay strong.",
    "Work hard and succeed.",
    "Your future is bright.",
    "Stay focused and driven.",
    "Never stop believing.",
    "Success comes from effort.",
    "Keep pushing and winning.",
    "Believe in your dreams.",
    "Work hard every day.",
    "Your success is near.",
    "Stay strong and focused.",
    "Keep striving and winning.",
    "Dream big and work hard.",
    "Success is earned through effort.",
    "Believe in yourself always.",
    "Work hard and stay positive.",
    "Keep moving forward daily.",
    "Your efforts lead to success.",
    "Stay dedicated and motivated.",
    "Success is a result of effort.",
    "Believe, work, and succeed.",
    "Keep pushing through challenges.",
    "Work hard and believe in you.",
    "Your success is your choice.",
    "Stay focused and work hard.",
    "Dream big and keep moving.",
    "Success is possible with effort.",
    "Believe and achieve your goals.",
    "Keep striving and believing.",
    "Work hard and never quit.",
    "Your future is in your hands.",
    "Stay positive and keep going.",
    "Success belongs to the persistent.",
    "Believe in your ability.",
    "Work hard and dream big.",
    "Keep moving and stay strong.",
    "Your effort creates your future.",
    "Stay dedicated and focused.",
    "Success is earned every day.",
    "Believe, work, and keep going.",
    "Keep pushing and striving.",
    "Work hard and stay motivated.",
    "Your success story is yours to write.",
    "Stay focused and keep working.",
    "Dream big and achieve.",
    "Success comes to those who work.",
    "Believe in yourself and succeed.",
    "Keep going and never stop.",
    "Work hard and be proud.",
    "Your future depends on you.",
    "Stay strong and keep trying.",
    "Success is within your grasp.",
    "Believe and never quit.",
    "Work hard and keep striving.",
    "Keep pushing and achieving.",
    "Your effort will be rewarded.",
    "Stay focused and dream big.",
    "Success is earned by action.",
    "Believe in your strength and work.",
    "Keep moving and stay motivated.",
    "Work hard and stay positive.",
    "Your future is bright if you try.",
    "Stay determined and focused.",
    "Success is the result of persistence.",
    "Believe, work, and achieve.",
    "Keep striving and never quit.",
    "Work hard and believe in success.",
    "Your success depends on your effort.",
    "Stay focused and keep pushing.",
    "Dream big and work hard daily.",
    "Success is earned, not given.",
    "Believe in your dreams and go for it.",
    "Keep moving forward every day.",
    "Work hard and never give up.",
    "Your future is yours to create.",
    "Stay positive and keep striving.",
    "Success comes from dedication.",
    "Believe, work, and keep moving.",
    "Keep pushing and stay strong.",
    "Work hard and achieve your goals.",
    "Your success is within reach.",
    "Stay focused and keep trying.",
    "Dream big and never stop.",
    "Success is earned with effort.",
    "Believe in yourself and your journey.",
    "Keep going and stay motivated.",
    "Work hard and make it happen.",
    "Your future depends on your work.",
    "Stay strong and believe.",
    "Success comes to those who try.",
    "Believe, work, and achieve your dreams.",
    "Keep striving and pushing forward.",
    "Work hard and stay committed.",
    "Your success is your responsibility.",
    "Stay focused and keep striving.",
    "Dream big and work for it.",
    "Success is earned one step at a time.",
    "Believe in yourself and your power.",
    "Keep moving forward with purpose.",
    "Work hard and never give up.",
    "Your future is bright if you keep trying.",
    "Stay motivated and keep pushing.",
    "Success comes from perseverance.",
    "Believe, work, and succeed.",
    "Keep striving and never stop.",
    "Work hard and stay focused.",
    "Your success story is waiting to be written.",
    "Stay positive and keep moving.",
    "Dream big and keep working.",
    "Success is earned through dedication.",
    "Believe in your strength and effort.",
    "Keep going and never quit.",
    "Work hard and stay determined.",
    "Your future depends on your effort.",
    "Stay focused and keep striving.",
    "Success comes to those who work hard.",
    "Believe, work, and achieve.",
    "Keep pushing and stay motivated.",
    "Work hard and never stop.",
    "Your success is in your hands.",
    "Stay positive and keep striving.",
    "Dream big and work hard every day.",
    "Success is earned, not given.",
    "Believe in yourself and keep moving.",
    "Keep going and stay focused.",
    "Work hard and achieve success.",
    "Your future is bright and full of potential.",
    "Stay motivated and keep working.",
    "Success comes from hard work and dedication.",
    "Believe, work, and keep striving.",
    "Keep pushing and never give up.",
    "Work hard and stay focused on your goals.",
    "Your success depends on your effort and attitude.",
    "Stay positive and keep moving forward.",
    "Dream big and work hard for it.",
    "Success is earned one step at a time.",
    "Believe in yourself and never quit.",
    "Keep going and stay motivated.",
    "Work hard and make your dreams real.",
    "Your future is yours to create with effort.",
    "Stay focused and keep striving.",
    "Success comes from persistence and hard work.",
    "Believe, work, and achieve your goals.",
    "Keep pushing and stay determined.",
    "Work hard and never stop trying.",
    "Your success story is waiting for you.",
    "Stay positive and keep working hard.",
    "Dream big and achieve your goals.",
    "Success is earned through effort and dedication.",
    "Believe in your strength and keep going.",
    "Keep moving forward and never quit.",
    "Work hard and stay motivated.",
    "Your future depends on your commitment.",
    "Stay focused and keep pushing forward.",
    "Success comes to those who never give up.",
    "Believe, work, and keep striving for greatness.",
    "Keep pushing and stay strong.",
    "Work hard and achieve your dreams.",
    "Your success is in your hands to make.",
    "Stay positive and keep working.",
    "Dream big and never stop trying.",
    "Success is earned one day at a time.",
    "Believe in yourself and your potential.",
    "Keep going and stay motivated.",
    "Work hard and make it happen.",
    "Your future is bright if you keep trying.",
    "Stay focused and keep striving.",
    "Success comes from hard work and persistence.",
    "Believe, work, and never give up.",
    "Keep pushing and stay determined.",
    "Work hard and stay focused on success.",
    "Your success depends on your effort.",
    "Stay positive and keep moving forward.",
    "Dream big and work hard every day.",
    "Success is earned, not given.",
    "Believe in yourself and keep pushing.",
    "Keep going and never stop striving.",
    "Work hard and achieve your goals.",
    "Your future is yours to create.",
    "Stay motivated and keep working.",
    "Success comes from dedication and effort.",
    "Believe, work, and keep striving.",
    "Keep pushing and stay motivated.",
    "Work hard and never give up on your dreams.",
    "Your success story is waiting to be written.",
    "Stay positive and keep striving for greatness.",
    "Dream big and work hard to achieve it.",
    "Success is earned through persistence.",
    "Believe in your power and keep going.",
    "Keep moving forward and stay focused.",
    "Work hard and achieve success.",
    "Your future depends on your effort and mindset.",
    "Stay focused and keep striving.",
    "Success comes to those who work hard and never quit.",
    "Believe, work, and keep pushing.",
    "Keep pushing and stay motivated.",
    "Work hard and achieve your dreams.",
    "Your success is in your hands to make happen.",
    "Stay positive and keep working hard.",
    "Dream big and never stop believing.",
    "Success is earned one step at a time.",
    "Believe in yourself and keep moving forward.",
    "Keep going and stay motivated.",
    "Work hard and make your dreams real.",
    "Your future is bright if you keep trying.",
    "Stay focused and keep striving.",
    "Success comes from hard work and dedication.",
    "Believe, work, and never give up.",
    "Keep pushing and stay determined.",
    "Work hard and stay focused on your goals.",
    "Your success depends on your effort and attitude.",
    "Stay positive and keep moving forward.",
    "Dream big and work hard for it.",
    "Success is earned one day at a time.",
    "Believe in yourself and never quit.",
    "Keep going and stay motivated.",
    "Work hard and make your dreams real.",
    "Your future is yours to create with effort.",
    "Stay focused and keep striving.",
    "Success comes from persistence and hard work.",
    "Believe, work, and achieve your goals.",
    "Keep pushing and stay determined.",
    "Work hard and never stop trying.",
    "Your success story is waiting for you.",
    "Stay positive and keep working hard.",
    "Dream big and achieve your goals.",
    "Success is earned through effort and dedication.",
    "Believe in your strength and keep going.",
    "Keep moving forward and never quit.",
    "Work hard and stay motivated.",
    "Your future depends on your commitment.",
    "Stay focused and keep pushing forward.",
    "Success comes to those who never give up.",
    "Believe, work, and keep striving for greatness.",
    "Keep pushing and stay strong.",
    "Work hard and achieve your dreams.",
    "Your success is in your hands to make.",
    "Stay positive and keep working.",
    "Dream big and never stop trying.",
    "Success is earned one day at a time.",
    "Believe in yourself and your potential.",
    "Keep going and stay motivated.",
    "Work hard and make it happen.",
    "Your future is bright if you keep trying.",
    "Stay focused and keep striving.",
    "Success comes from hard work and persistence.",
    "Believe, work, and never give up.",
    "Keep pushing and stay determined.",
    "Work hard and stay focused on success.",
    "Your success depends on your effort.",
    "Stay positive and keep moving forward.",
    "Dream big and work hard every day.",
    "Success is earned, not given.",
    "Believe in yourself and keep pushing.",
    "Keep going and never stop striving.",
    "Work hard and achieve your goals.",
    "Your future is yours to create.",
    "Stay motivated and keep working.",
    "Success comes from dedication and effort.",
    "Believe, work, and keep striving.",
    "Keep pushing and stay motivated.",
    "Work hard and never give up on your dreams.",
    "Your success story is waiting to be written.",
    "Stay positive and keep striving for greatness.",
    "Dream big and work hard to achieve it.",
    "Success is earned through persistence.",
    "Believe in your power and keep going.",
    "Keep moving forward and stay focused.",
    "Work hard and achieve success.",
    "Your future depends on your effort and mindset.",
    "Stay focused and keep striving.",
    "Success comes to those who work hard and never quit.",
    "Believe, work, and keep pushing.",
    "Keep pushing and stay motivated.",
    "Work hard and achieve your dreams.",
    "Your success is in your hands to make happen.",
    "Stay positive and keep working hard.",
    "Dream big and never stop believing.",
    "Success is earned one step at a time.",
    "Believe in yourself and keep moving forward.",
    "Keep going and stay motivated.",
    "Work hard and make your dreams real.",
    "Your future is bright if you keep trying.",
    "Stay focused and keep striving.",
    "Success comes from hard work and dedication.",
    "Believe, work, and never give up.",
    "Keep pushing and stay determined.",
    "Work hard and stay focused on your goals.",
    "Your success depends on your effort and attitude.",
    "Stay positive and keep moving forward.",
    "Dream big and work hard for it.",
    "Success is earned one day at a time.",
    "Believe in yourself and never quit.",
    "Keep going and stay motivated.",
    "Work hard and make your dreams real.",
    "Your future is yours to create with effort.",
    "Stay focused and keep striving.",
    "Success comes from persistence and hard work.",
    "Believe, work, and achieve your goals.",
    "Keep pushing and stay determined.",
    "Work hard and never stop trying.",
    "Your success story is waiting for you.",
    "Stay positive and keep working hard.",
    "Dream big and achieve your goals.",
    "Success is earned through effort and dedication.",
    "Believe in your strength and keep going.",
    "Keep moving forward and never quit.",
    "Work hard and stay motivated.",
    "Your future depends on your commitment.",
    "Stay focused and keep pushing forward.",
    "Success comes to those who never give up.",
    "Believe, work, and keep striving for greatness.",
    "Keep pushing and stay strong.",
    "Work hard and achieve your dreams.",
    "Your success is in your hands to make.",
    "Stay positive and keep working.",
    "Dream big and never stop trying.",
    "Success is earned one day at a time.",
    "Believe in yourself and your potential.",
    "Keep going and stay motivated.",
    "Work hard and make it happen.",
    "Your future is bright if you keep trying.",
    "Stay focused and keep striving.",
    "Success comes from hard work and persistence.",
    "Believe, work, and never give up.",
    "Keep pushing and stay determined.",
    "Work hard and stay focused on success.",
    "Your success depends on your effort.",
    "Stay positive and keep moving forward.",
    "Dream big and work hard every day.",
    "Success is earned, not given.",
    "Believe in yourself and keep pushing.",
    "Keep going and never stop striving.",
    "Work hard and achieve your goals.",
    "Your future is yours to create.",
    "Stay motivated and keep working.",
    "Success comes from dedication and effort.",
    "Believe, work, and keep striving.",
    "Keep pushing and stay motivated.",
    "Work hard and never give up on your dreams.",
    "Your success story is waiting to be written.",
    "Stay positive and keep striving for greatness.",
    "Dream big and work hard to achieve it.",
    "Success is earned through persistence.",
    "Believe in your power and keep going.",
    "Keep moving forward and stay focused.",
    "Work hard and achieve success.",
    "Your future depends on your effort and mindset.",
    "Stay focused and keep striving.",
    "Success comes to those who work hard and never quit.",
    "Believe, work, and keep pushing.",
    "Keep pushing and stay motivated.",
    "Work hard and achieve your dreams.",
    "Your success is in your hands to make happen.",
    "Stay positive and keep working hard.",
    "Dream big and never stop believing.",
    "Success is earned one step at a time.",
    "Believe in yourself and keep moving forward.",
    "Keep going and stay motivated.",
    "Work hard and make your dreams real.",
    "Your future is bright if you keep trying.",
    "Stay focused and keep striving.",
    "Success comes from hard work and dedication.",
    "Believe, work, and never give up.",
    "Keep pushing and stay determined.",
    "Work hard and stay focused on your goals.",
    "Your success depends on your effort and attitude.",
    "Stay positive and keep moving forward.",
    "Dream big and work hard for it.",
    "Success is earned one day at a time.",
    "Believe in yourself and never quit.",
    "Keep going and stay motivated.",
    "Work hard and make your dreams real.",
    "Your future is yours to create with effort.",
    "Stay focused and keep striving.",
    "Success comes from persistence and hard work.",
    "Believe, work, and achieve your goals.",
    "Keep pushing and stay determined.",
    "Work hard and never stop trying.",
    "Your success story is waiting for you.",
    "Stay positive and keep working hard.",
    "Dream big and achieve your goals.",
    "Success is earned through effort and dedication.",
    "Believe in your strength and keep going.",
    "Keep moving forward and never quit.",
    "Work hard and stay motivated.",
    "Your future depends on your commitment.",
    "Stay focused and keep pushing forward.",
    "Success comes to those who never give up.",
    "Believe, work, and keep striving for greatness.",
    "Keep pushing and stay strong.",
    "Work hard and achieve your dreams.",
    "Your success is in your hands to make.",
    "Stay positive and keep working.",
    "Dream big and never stop trying.",
    "Success is earned one day at a time.",
    "Believe in yourself and your potential.",
    "Keep going and stay motivated.",
    "Work hard and make it happen.",
    "Your future is bright if you keep trying.",
    "Stay focused and keep striving.",
    "Success comes from hard work and persistence.",
    "Believe, work, and never give up.",
    "Keep pushing and stay determined.",
    "Work hard and stay focused on success.",
    "Your success depends on your effort.",
    "Stay positive and keep moving forward.",
    "Dream big and work hard every day.",
    "Success is earned, not given.",
    "Believe in yourself and keep pushing.",
    "Keep going and never stop striving.",
    "Work hard and achieve your goals.",
    "Your future is yours to create.",
    "Stay motivated and keep working.",
    "Success comes from dedication and effort.",
    "Believe, work, and keep striving.",
    "Keep pushing and stay motivated.",
    "Work hard and never give up on your dreams.",
    "Your success story is waiting to be written.",
    "Stay positive and keep striving for greatness.",
    "Dream big and work hard to achieve it.",
    "Success is earned through persistence.",
    "Believe in your power and keep going.",
    "Keep moving forward and stay focused.",
    "Work hard and achieve success.",
    "Your future depends on your effort and mindset.",
    "Stay focused and keep striving.",
    "Success comes to those who work hard and never quit.",
    "Believe, work, and keep pushing.",
    "Keep pushing and stay motivated.",
    "Work hard and achieve your dreams.",
    "Your success is in your hands to make happen.",
    "Stay positive and keep working hard.",
    "Dream big and never stop believing.",
    "Success is earned one step at a time.",
    "Believe in yourself and keep moving forward.",
    "Keep going and stay motivated.",
    "Work hard and make your dreams real.",
    "Your future is bright if you keep trying.",
    "Stay focused and keep striving.",
    "Success comes from hard work and dedication.",
    "Believe, work, and never give up.",
    "Keep pushing and stay determined.",
    "Work hard and stay focused on your goals.",
    "Your success depends on your effort and attitude.",
    "Stay positive and keep moving forward.",
    "Dream big and work hard for it.",
    "Success is earned one day at a time.",
    "Believe in yourself and never quit.",
    "Keep going and stay motivated.",
    "Work hard and make your dreams real.",
    "Your future is yours to create with effort.",
    "Stay focused and keep striving.",
    "Success comes from persistence and hard work.",
    "Believe, work, and achieve your goals.",
    "Keep pushing and stay determined.",
    "Work hard and never stop trying.",
    "Your success story is waiting for you.",
    "Stay positive and keep working hard.",
    "Dream big and achieve your goals.",
    "Success is earned through effort and dedication.",
    "Believe in your strength and keep going.",
    "Keep moving forward and never quit.",
    "Work hard and stay motivated.",
    "Your future depends on your commitment.",
    "Stay focused and keep pushing forward.",
    "Success comes to those who never give up.",
    "Believe, work, and keep striving for greatness.",
    "Keep pushing and stay strong.",
    "Work hard and achieve your dreams.",
    "Your success is in your hands to make.",
    "Stay positive and keep working.",
    "Dream big and never stop trying.",
    "Success is earned one day at a time.",
    "Believe in yourself and your potential.",
    "Keep going and stay motivated.",
    "Work hard and make it happen.",
    "Your future is bright if you keep trying.",
    "Stay focused and keep striving.",
    "Success comes from hard work and persistence.",
    "Believe, work, and never give up.",
    "Keep pushing and stay determined.",
    "Work hard and stay focused on success.",
    "Your success depends on your effort.",
    "Stay positive and keep moving forward.",
    "Dream big and work hard every day.",
    "Success is earned, not given.",
    "Believe in yourself and keep pushing.",
    "Keep going and never stop striving.",
    "Work hard and achieve your goals.",
    "Your future is yours to create.",
    "Stay motivated and keep working.",
    "Success comes from dedication and effort.",
    "Believe, work, and keep striving.",
    "Keep pushing and stay motivated.",
    "Work hard and never give up on your dreams.",
    "Your success story is waiting to be written.",
    "Stay positive and keep striving for greatness.",
    "Dream big and work hard to achieve it.",
    "Success is earned through persistence.",
    "Believe in your power and keep going.",
    "Keep moving forward and stay focused.",
    "Work hard and achieve success.",
    "Your future depends on your effort and mindset.",
    "Stay focused and keep striving.",
    "Success comes to those who work hard and never quit.",
    "Believe, work, and keep pushing.",
    "Keep pushing and stay motivated.",
    "Work hard and achieve your dreams.",
    "Your success is in your hands to make happen.",
    "Stay positive and keep working hard.",
    "Dream big and never stop believing.",
    "Success is earned one step at a time.",
    "Believe in yourself and keep moving forward.",
  
];

const getBrowserTimezone = () => {
    if (typeof window === 'undefined') return 'UTC';
    try {
      return Intl.DateTimeFormat().resolvedOptions().timeZone;
    } catch (e) {
      console.warn('Could not detect timezone, defaulting to UTC.');
      return 'UTC';
    }
};

const isValidTimezone = (tz: string) => {
    try {
        Intl.DateTimeFormat(undefined, { timeZone: tz });
        return true;
    } catch (e) {
        return false;
    }
}


export function DashboardHeader() {
  const { user } = useAuth();
  const [greeting, setGreeting] = useState('');
  const [quote, setQuote] = useState('');
  const [currentDate, setCurrentDate] = useState('');
  const [currentTime, setCurrentTime] = useState('');
  const [timezone, setTimezone] = useState(getBrowserTimezone());
  const streak = 3; // Mock data

  useEffect(() => {
    if (user) {
      const userDocRef = doc(db, 'users', user.uid);
      const unsubscribe = onSnapshot(userDocRef, (docSnap) => {
        const savedTimezone = docSnap.data()?.calendarSettings?.timezone;
        setTimezone(isValidTimezone(savedTimezone) ? savedTimezone : getBrowserTimezone());
      });
      return () => unsubscribe();
    } else {
      // Reset to browser default on logout
      setTimezone(getBrowserTimezone());
    }
  }, [user]);


  useEffect(() => {
    const hour = new Date().getHours();
    if (hour < 12) setGreeting('Good Morning');
    else if (hour < 18) setGreeting('Good Afternoon');
    else setGreeting('Good Evening');
    
    setQuote(quotes[Math.floor(Math.random() * quotes.length)]);

    const updateDateTime = () => {
      const now = new Date();
      const effectiveTimezone = isValidTimezone(timezone) ? timezone : 'UTC';

      try {
        setCurrentDate(now.toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric', timeZone: effectiveTimezone }));
        setCurrentTime(now.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit', timeZone: effectiveTimezone, hour12: true }));
      } catch (e) {
        // Fallback to local time if timezone is invalid
        console.error("Invalid timezone:", timezone, e);
        setCurrentDate(now.toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' }));
        setCurrentTime(now.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit', hour12: true }));
      }
    };

    updateDateTime();
    const timerId = setInterval(updateDateTime, 1000);

    return () => clearInterval(timerId);
  }, [timezone]);

  const displayName = user?.displayName?.split(' ')[0] || 'Student';

  return (
    <header className="flex items-center justify-between p-4">
      <div>
        <h1 className="font-headline text-2xl md:text-3xl font-bold text-foreground">
          {greeting ? `${greeting}, ${displayName} 👋` : `Welcome, ${displayName} 👋`}
        </h1>
        <p className="text-muted-foreground text-sm mt-1">
          {quote ? `"${quote}"` : "Let's make today productive."}
        </p>
      </div>
      <div className="flex items-center gap-2">
         <div className="hidden sm:flex items-center gap-6">
            <div className="text-right">
                <p className="font-mono text-lg font-semibold tracking-tighter text-foreground">{currentTime}</p>
                <p className="text-xs text-muted-foreground">{currentDate}</p>
            </div>
            <div className="text-center">
                <div className="flex items-center justify-center gap-1 text-orange-400">
                    <p className="text-2xl font-bold">{streak}</p>
                    <Flame className="h-5 w-5" />
                </div>
                <p className="text-xs text-muted-foreground">Day Streak</p>
            </div>
         </div>
         <DashboardCustomizer>
          <button className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-secondary text-secondary-foreground transition-colors hover:bg-secondary/80">
            <Palette className="h-5 w-5" />
          </button>
         </DashboardCustomizer>
         <AceMascot className="h-12 w-12 hidden sm:block" />
        <SidebarTrigger className="md:hidden" />
      </div>
    </header>
  );
}
